name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
         cd hw4/tinyurl
         mvn package -DskipTests
         cd ../
         cp tinyurl/target/tinyurl-0.0.1-SNAPSHOT.jar .
         docker build -t ruishaopu561/seproject:v1 -f tinyurl.dockerfile .
         echo "docker build successfully!"
